=encoding UTF-8

=head1 NAME

Scientist - Test new code against old.

=for HTML
<a href=https://travis-ci.org/lancew/Scientist><img src=https://api.travis-ci.org/lancew/Scientist.svg></a>
<a href=https://coveralls.io/github/lancew/Scientist><img src=https://coveralls.io/repos/lancew/Scientist/badge.svg></a>
<a href=https://metacpan.org/pod/Scientist><img src="https://badge.fury.io/pl/Scientist.svg"></a>
<a href=https://github.com/lancew/Scientist/issues><img src=https://img.shields.io/github/issues/lancew/Scientist.svg></a>

=head1 DESCRIPTION

Perl module inspired by https://github.com/github/scientist ( http://githubengineering.com/scientist/ )

=head1 SYNOPSIS

    use Scientist;

    sub old_code {
        return 10;
    }

    sub new_code {
        return 20;
    }

    my $experiment = Scientist->new( 
        experiment => 'MyTest',
        use => \&old_code,
        try => \&new_code,
    );
    
    my $answer = $experiment->run;

    say "The number ten is $answer";
    warn 'There was a mismatch between control and candidate'
        if $experiment->result->{'mismatched'};

    say 'Timings:';
    say 'Control code:   ', $experiement->result->{control}{duration}, ' microseconds';
    say 'Candidate code: ', $experiement->result->{candidate}{duration}, ' microseconds';

=head1 Introduction

This module is inspired by the Scientist ruby code released by GitHub under the MIT license in 2015/2016.

In February 2016 I started writing this Perl module to bring similar ideas to Perl.

Please get involved in this module; contact lancew@cpan.org with ideas, suggestions; support, etc.

This code is also released under the MIT license to match the original Ruby implementation.

=head1 AUTHOR
 
Lance Wicks <lancew@cpan.org>
 
=head1 COPYRIGHT AND LICENSE

This software is Copyright (c) 2016 by Lance Wicks.
 
This is free software, licensed under:
 
  The MIT (X11) License
 
The MIT License
 
Permission is hereby granted, free of charge, to any person
obtaining a copy of this software and associated
documentation files (the "Software"), to deal in the Software
without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to
whom the Software is furnished to do so, subject to the
following conditions:
 
The above copyright notice and this permission notice shall
be included in all copies or substantial portions of the
Software.
 
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT
WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR
PURPOSE AND NONINFRINGEMENT. IN NO EVENT
SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.

=head1 SEE ALSO

http://www.infoq.com/news/2016/02/github-scientist-refactoring

http://githubengineering.com/scientist/

https://news.ycombinator.com/item?id=11104781

https://github.com/ziyasal/scientist.js
